# Airthematic operation

In [1]:
import numpy as np
var1=np.array([1,2,3,4])
varAdd=var1+3
print(varAdd)
# similarly
varadd=np.add(var1,3)
print (varadd)

[4 5 6 7]
[4 5 6 7]


In [2]:
var1=np.array([2,3,45])
varsubtract=np.subtract(var1,4)
print(varsubtract)

[-2 -1 41]


In [3]:
var1=np.array([2,3,45])
varmultiply=np.multiply(var1,4)
print(varmultiply)

[  8  12 180]


In [4]:
var1=np.array([2,3,45])
var2=np.array([4,5,6,])
varmultiply=np.multiply(var1,var2)
print(varmultiply)
#similarly all function we can perform like mod,division,power,reciprocal etc

[  8  15 270]


# 2D Array

In [5]:
var21=np.array([[1,2,3,4],[1,2,34,5]])
var22=np.array([[1,2,3,4],[1,2,34,5]])


varAdd=var21+var22
print(varAdd)

[[ 2  4  6  8]
 [ 2  4 68 10]]


In [6]:
var21=np.array([[1,2,3,4],[1,2,34,5]])
var22=np.array([[1,2,3,4],[1,2,34,5]])


varAdd=var21*var22
print(varAdd)

[[   1    4    9   16]
 [   1    4 1156   25]]
