In [1]:
import numpy as np

In [2]:
my_arr=np.arange(1000000)
my_list=list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2=my_arr*2

CPU times: total: 78.1 ms
Wall time: 66.7 ms


# The NumPy ndarray: A Multidimensional Array Object

In [4]:
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])
array1+array2

array([ 6,  8, 10, 12])

In [5]:
array1=np.array([[1,2,3,4],[5,6,7,8]])
array2=np.array([[1,2,3,4],[5,6,7,8]])
array1+array2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [6]:
array1=np.array([[1,2,3,4],[5,6,7,8]])
# to checking the dimension of array
array1.ndim

2

In [8]:
# to checking the rows and column simply known as shape
array1.shape

(2, 4)

In [9]:
l=[]
for i in range(10):
    l.append(i)

# to convert the numbers in array
array1=np.array(l)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Two dimsnional Array

In [10]:
arra1=np.array([[1,2,3,4],[5,6,7,8]])
arra1


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# checking the shape of array
arra1.shape
# there is 2 rows and 4 columns in above expression

(2, 4)

In [12]:
arra1.ndim

2

In [13]:
arra1.dtype

dtype('int32')

In [16]:
# we use eye function to get the identity metrix of given dimension
np.eye(3,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])